"""add is_deleted to drawings

Revision ID: 600652ca9d1a
Revises: 979907760628
Create Date: 2026-03-08 11:17:45.692716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600652ca9d1a'
down_revision = '979907760628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drawings', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
    # ### end Alembic commands ###