"""make email nullable

Revision ID: 979907760628
Revises: 10fa525f71cd
Create Date: 2026-03-07 18:33:46.434950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979907760628'
down_revision = '10fa525f71cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
